apiVersion: v1
kind: PersistentVolume
metadata:
  name: concourse-postgresql
  labels:
    type: amazonEBS
    app: postgresql
    release: concourse
    role: master
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-04135b4c2e7e92de9
    fsType: gp2