apiVersion: v1
kind: PersistentVolume
metadata:
  name: concourse-workers
  labels:
    type: amazonEBS
    app: concourse-worker
    release: concourse
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: ${VOLUME_ID}
    fsType: gp2